2020-11-23 14:01:37,028 [INFO] root consoleworker.py:434	Log file created
2020-11-23 14:01:37,029 [INFO] root consoleworker.py:438	Logging handler <logging.FileHandler object at 0x7f8976598b90> added
2020-11-23 14:01:37,030 [INFO] root consoleworker.py:438	Logging handler <logging.StreamHandler object at 0x7f89765e17d0> added
2020-11-23 14:01:37,030 [INFO] root consoleworker.py:438	Logging handler <logging.StreamHandler object at 0x7f89765869d0> added
2020-11-23 14:01:37,031 [INFO] root consoleworker.py:373	Created a folder for the test. /var/loadtest/logs/2020-11-23_14-01-36.919145
2020-11-23 14:01:37,032 [INFO] yandextank.core.tankcore tankcore.py:237	Configuring plugins...
2020-11-23 14:01:37,034 [INFO] yandextank.core.tankcore tankcore.py:190	Loading plugins...
2020-11-23 14:01:37,035 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin phantom from yandextank.plugins.Phantom
2020-11-23 14:01:37,036 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin rcheck from yandextank.plugins.ResourceCheck
2020-11-23 14:01:37,037 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin json_report from yandextank.plugins.JsonReport
2020-11-23 14:01:37,046 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin overload from yandextank.plugins.DataUploader
2020-11-23 14:01:37,047 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin rcassert from yandextank.plugins.RCAssert
2020-11-23 14:01:37,048 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin console from yandextank.plugins.Console
2020-11-23 14:01:37,048 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin shellexec from yandextank.plugins.ShellExec
2020-11-23 14:01:37,049 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin autostop from yandextank.plugins.Autostop
2020-11-23 14:01:37,050 [DEBUG] yandextank.core.tankcore tankcore.py:212	Plugin instances: {'plugin_phantom': <yandextank.plugins.Phantom.plugin.Plugin object at 0x7f89762d7f50>, 'plugin_autostop': <yandextank.plugins.Autostop.plugin.Plugin object at 0x7f89762daf10>, 'plugin_shellexec': <yandextank.plugins.ShellExec.plugin.Plugin object at 0x7f89762da6d0>, 'plugin_console': <yandextank.plugins.Console.plugin.Plugin object at 0x7f89762da590>, 'plugin_rcassert': <yandextank.plugins.RCAssert.plugin.Plugin object at 0x7f89762da4d0>, 'plugin_rcheck': <yandextank.plugins.ResourceCheck.plugin.Plugin object at 0x7f89762d7e10>, 'plugin_overload': <yandextank.plugins.DataUploader.plugin.Plugin object at 0x7f89762d79d0>, 'plugin_json_report': <yandextank.plugins.JsonReport.plugin.Plugin object at 0x7f8976601990>}
2020-11-23 14:01:37,051 [DEBUG] yandextank.core.tankcore tankcore.py:244	Configuring <yandextank.plugins.Phantom.plugin.Plugin object at 0x7f89762d7f50>
2020-11-23 14:01:37,052 [DEBUG] yandextank.core.tankcore tankcore.py:391	Searching for plugin: <class 'yandextank.plugins.Autostop.plugin.Plugin'>
2020-11-23 14:01:37,064 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2020-11-23_14-01-36.919145/answ_wrlEPD.log
2020-11-23 14:01:37,068 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2020-11-23_14-01-36.919145/phout_YkL8K1.log
2020-11-23 14:01:37,069 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2020-11-23_14-01-36.919145/phantom_stat_1LWRkP.log
2020-11-23 14:01:37,073 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2020-11-23_14-01-36.919145/phantom_X69sZQ.log
2020-11-23 14:01:37,074 [DEBUG] yandextank.common.util util.py:479	Trying to resolve address string: 127.0.0.1:5555
2020-11-23 14:01:37,076 [DEBUG] yandextank.common.util util.py:516	Parsing port
2020-11-23 14:01:37,077 [DEBUG] yandextank.common.util util.py:527	Lookup result: [(2, 1, 6, '', ('127.0.0.1', 5555)), (2, 2, 17, '', ('127.0.0.1', 5555)), (2, 3, 0, '', ('127.0.0.1', 5555))]
2020-11-23 14:01:37,077 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 127.0.0.1 and port 5555
2020-11-23 14:01:37,080 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [127.0.0.1]:5555 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

2020-11-23 14:01:37,080 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [127.0.0.1]:5555
2020-11-23 14:01:37,081 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [127.0.0.1]:5555
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [127.0.0.1]:5555, use phantom.connection_test=0 to disable it
2020-11-23 14:01:37,083 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 127.0.0.1 and port 5555
2020-11-23 14:01:37,085 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [127.0.0.1]:5555 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

2020-11-23 14:01:37,086 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [127.0.0.1]:5555
2020-11-23 14:01:37,086 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [127.0.0.1]:5555
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [127.0.0.1]:5555, use phantom.connection_test=0 to disable it
2020-11-23 14:01:37,089 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 127.0.0.1 and port 5555
2020-11-23 14:01:37,094 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [127.0.0.1]:5555 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

2020-11-23 14:01:37,095 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [127.0.0.1]:5555
2020-11-23 14:01:37,096 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [127.0.0.1]:5555
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [127.0.0.1]:5555, use phantom.connection_test=0 to disable it
2020-11-23 14:01:37,099 [ERROR] root consoleworker.py:268	Exception occurred:
<type 'exceptions.RuntimeError'>: All connection attempts failed for 127.0.0.1, use {phantom.connection_test: false} to disable it
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/consoleworker.py", line 375, in run
    self.core.plugins_configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/tankcore.py", line 245, in plugins_configure
    plugin.configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 72, in configure
    self.phantom_config = self.phantom.config_file

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 81, in phantom
    self._phantom.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 95, in read_config
    stream.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 275, in read_config
    self.address, do_test_connect, explicit_port)

  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 555, in resolve
    raise RuntimeError(msg % address_str)

2020-11-23 14:01:37,102 [INFO] root consoleworker.py:269	Trying to clean up
2020-11-23 14:01:37,103 [INFO] yandextank.core.tankcore tankcore.py:561	Releasing lock: /var/lock/lunapark_tkydHq.lock
2020-11-23 14:01:37,110 [WARNING] root consoleworker.py:408	Job number is not available yet
2020-11-23 14:01:37,111 [WARNING] root consoleworker.py:415	Job number is not available yet
2020-11-23 14:01:37,123 [DEBUG] yandextank.core.tankcore tankcore.py:367	Collecting artifacts
2020-11-23 14:01:37,124 [INFO] yandextank.core.tankcore tankcore.py:368	Artifacts dir: /var/loadtest/logs/2020-11-23_14-01-36.919145
2020-11-23 14:01:37,124 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2020-11-23_14-01-36.919145/answ_wrlEPD.log to /var/loadtest/logs/2020-11-23_14-01-36.919145/answ_wrlEPD.log
2020-11-23 14:01:37,128 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2020-11-23_14-01-36.919145/answ_wrlEPD.log
2020-11-23 14:01:37,130 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2020-11-23_14-01-36.919145/phantom_stat_1LWRkP.log to /var/loadtest/logs/2020-11-23_14-01-36.919145/phantom_stat_1LWRkP.log
2020-11-23 14:01:37,134 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2020-11-23_14-01-36.919145/phantom_stat_1LWRkP.log
2020-11-23 14:01:37,135 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: validation_error.yaml to /var/loadtest/logs/2020-11-23_14-01-36.919145/validation_error.yaml
2020-11-23 14:01:37,136 [WARNING] yandextank.core.tankcore tankcore.py:424	File not found to collect: validation_error.yaml
2020-11-23 14:01:37,137 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2020-11-23_14-01-36.919145/phout_YkL8K1.log to /var/loadtest/logs/2020-11-23_14-01-36.919145/phout_YkL8K1.log
2020-11-23 14:01:37,143 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2020-11-23_14-01-36.919145/phout_YkL8K1.log
2020-11-23 14:01:37,144 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2020-11-23_14-01-36.919145/phantom_X69sZQ.log to /var/loadtest/logs/2020-11-23_14-01-36.919145/phantom_X69sZQ.log
2020-11-23 14:01:37,148 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2020-11-23_14-01-36.919145/phantom_X69sZQ.log
